export const AUDIT_ENTITY_TYPES = {
  USER: "USER",
  JOB_OFFER: "JOB_OFFER",
  JOB_APPLICATION: "JOB_APPLICATION",
  PAYMENT: "PAYMENT",
  PAYMENT_WEBHOOK_EVENT: "PAYMENT_WEBHOOK_EVENT",
  CANDIDATE_DOCUMENT: "CANDIDATE_DOCUMENT",
} as const;
