FROM node:20-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json

RUN npm install

COPY . .

RUN npm run prisma:generate && npm run build -w apps/api

EXPOSE 4000

CMD ["npm", "run", "start", "-w", "apps/api"]
